name: Kubescape Demo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mitre-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

      - name: Scan YAML files for mitre check
        run: kubescape scan framework mitre *.yaml
